# Generated by Django 4.0.2 on 2024-05-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_care_services', '0002_serviceregistrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistrations',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_care_services.services'),
        ),
    ]
