# Generated by Django 4.0.2 on 2024-05-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_countrydialcodes_country_name'),
        ('home_care_services', '0004_alter_serviceregistrations_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistrations',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.countrydialcodes'),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='mobile_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceregistrations',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='serviceregistrations',
            name='service',
            field=models.CharField(max_length=15),
        ),
    ]
