# Generated by Django 4.0.2 on 2024-05-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_care_services', '0005_serviceregistrations_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistrations',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_care_services.services'),
        ),
    ]
