# Generated by Django 4.0.2 on 2024-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_care_services', '0006_alter_serviceregistrations_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistrations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
