# Generated by Django 4.0.2 on 2024-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_care_services', '0007_serviceregistrations_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistrations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
