# Generated by Django 4.0.2 on 2024-03-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeyondBordersDependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('relation', models.CharField(max_length=15)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('current_issue_treatment_expected', models.TextField()),
                ('health_insurance_details', models.TextField()),
                ('address', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.countrydialcodes')),
            ],
        ),
    ]
