# Generated by Django 4.0.2 on 2024-03-14 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beyond_borders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyondbordersdependents',
            name='refered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
