# Generated by Django 4.0.2 on 2024-03-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beyond_borders', '0002_beyondbordersdependents_refered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beyondbordersdependents',
            name='current_issue_treatment_expected',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='beyondbordersdependents',
            name='health_insurance_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='beyondbordersdependents',
            name='refered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
