# Generated by Django 4.0.2 on 2024-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyond_borders', '0003_alter_beyondbordersdependents_current_issue_treatment_expected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyondbordersdependents',
            name='membership_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
