# Generated by Django 4.0.2 on 2024-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyond_borders', '0005_alter_beyondbordersdependents_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyondbordersdependents',
            name='image_filename',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
