# Generated by Django 4.0.2 on 2024-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_forgot_password_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
