# Generated by Django 4.0.2 on 2024-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydialcodes',
            name='country_name',
            field=models.CharField(max_length=40),
        ),
    ]
