# Generated by Django 4.0.2 on 2024-03-31 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Basic', 'Basic'), ('Essential', 'Essential'), ('Privilage', 'Privilage'), ('Vip', 'Vip')], max_length=15)),
                ('card_fee', models.IntegerField()),
                ('waiting_period', models.IntegerField()),
                ('preventive_health_check_up', models.IntegerField()),
                ('free_doctor_consultation', models.IntegerField()),
                ('pharmacy_discount', models.IntegerField()),
                ('lab_radiology_discount', models.IntegerField()),
                ('personal_accident_insurance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_radiology_wallet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('members_covered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCardRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community_health_cards.membershipcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
