# Generated by Django 4.0.2 on 2024-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcard',
            name='personal_accident_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
