# Generated by Django 4.0.2 on 2024-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_health_cards', '0002_alter_membershipcard_personal_accident_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcard',
            name='lab_radiology_wallet',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membershipcard',
            name='personal_accident_insurance',
            field=models.IntegerField(),
        ),
    ]
