# Generated by Django 4.0.2 on 2024-05-27 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_health_cards', '0003_alter_membershipcard_lab_radiology_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcardregistrations',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_health_cards.membershipcard'),
        ),
        migrations.AlterField(
            model_name='membershipcardregistrations',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
